Added OFDM support
signetlabdei/DESERT_Underwater pull request #3
Opened 2022-11-02 02:13 UTC by sarafalleni05

Added: 
OFDM phy module 
OFDM interference module
OFDM Aloha compatible with OFDM physical layer 
tcl test file as usage example
msg_displayer class for convenience 
modifications to previous classes to better support OFDM doings

2022-11-02 23:05 UTC, fedefava86 requested changes

2022-11-02 23:05 UTC, fedefava86 commented on DESERT_Framework/DESERT/Makefile.am
> -	physical/uwmodem \
Is there a reason why you remove those modules are removed from Makefile.am?

2022-11-02 23:05 UTC, fedefava86 commented on DESERT_Framework/DESERT/Makefile.am
> -    physical/uwahoimodem \
same as before

2022-11-02 23:05 UTC, fedefava86 commented on DESERT_Framework/DESERT/configure.ac
> -DESERT_CPPFLAGS="$DESERT_CPPFLAGS "'-I$(top_srcdir)/physical/uwmodem'
same as before

2022-11-02 23:05 UTC, fedefava86 commented on DESERT_Framework/DESERT/data_link/uw-ofdm-aloha/uw-ofdm-aloha.cpp
> +    : ack_timer(this), backoff_timer(this), txsn(1), last_sent_data_id(-1), curr_data_pkt(0),
Only an aesthetic stuff, but we usually prefer to have those variables one per line. It improves readability in our opinion

2022-11-04 17:08 UTC, fedefava86 requested changes

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/data_link/uw-ofdm-aloha/uw-ofdm-aloha.cpp
> +void UWOFDMAloha::waitForUser()
This method is not used anywhere. It was used at the real beginning of protocols implementation to do a "step by step" execution introducing a rough breakpoint. I think you can remove it :)

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/interference/uwinterferenceofdm/UwInterferenceCollisionCounterInitTcl.cpp
> +static char code[] =
I think this is a compilation artifact, you shall remove this file

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/interference/uwinterferenceofdm/uwinterferenceofdm.cpp
> +		std::cerr << "uwinterference::removeFromInterference, "
I think here we have a possible segfault or a general crash. you here check that `power_list` is empy. If it is, you print an error, but you do not return from method, and you do something if this is not empy. However, after the `else` branch, you still do something with an empy list

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/interference/uwinterferenceofdm/uwinterferenceofdm.cpp
> +				  << " ,total power: " << power_list.back().sum_power
from here `power_list `could be empty

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/data_link/uw-ofdm-aloha/uw-ofdm-aloha.cpp
> +    cout << NOW << "  UWOFDMAloha (" << addr
This shall be indented w/ respect of previous line

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/data_link/uw-ofdm-aloha/uw-ofdm-aloha.cpp
> +        displayCarriers((*it_p).second);
indentation

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/data_link/uw-ofdm-aloha/uw-ofdm-aloha.h
> +#include "../../physical/uwofdmphy/uwofdmphy_hdr.h"
We usually try to avoid to use relative paths on includes. The path should be automatically setup by Makefile flags, exactly like you are doing for `mphy`

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/physical/uwofdmphy/uwofdmphy.h
> +#include "../../msg-display/msg-display.h"
Try to avoid to use relative paths in include. Paths are resolved by Makefile vars
```suggestion
#include "msg-display.h"
```

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/samples/desert_samples/test_ofdmaloha_desert_integration.tcl
> +        set opt(modulation)     [lindex $argv 4]
Index of argv is broken, should be 3
```suggestion
        set opt(modulation)     [lindex $argv 3]
```

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/samples/desert_samples/test_ofdmaloha_desert_integration.tcl
> +        set opt(AckInBand)     [lindex $argv 5]
```suggestion
        set opt(AckInBand)     [lindex $argv 4]
```

2022-11-04 17:08 UTC, fedefava86 commented on DESERT_Framework/DESERT/samples/desert_samples/test_ofdmaloha_desert_integration.tcl
> +        set opt(pktsize)        [lindex $argv 6]
```suggestion
        set opt(pktsize)        [lindex $argv 5]
```

2022-11-08 17:20 UTC, sarafalleni05 commented on DESERT_Framework/DESERT/interference/uwinterferenceofdm/uwinterferenceofdm.cpp
> +		std::cerr << "uwinterference::removeFromInterference, "
I will return in that case. However this code is written in the same way in the original interference module, maybe you also want to change it over there.

2022-11-09 11:29 UTC, fedefava86 commented on DESERT_Framework/DESERT/interference/uwinterferenceofdm/uwinterferenceofdm.cpp
> +		std::cerr << "uwinterference::removeFromInterference, "
Yes, definitely. So we have a potential crash too, good to know. Thank you!

2022-11-09 16:51 UTC, fedefava86 approved these changes

2022-11-09 16:52 UTC, merged