Reservation Based Adaptive MAC (RAMAC) protocol added
signetlabdei/DESERT_Underwater pull request #6
Opened 2023-02-07 22:58 UTC by sarafalleni05

OFDM-based MAC protocol 
RTS and CTS used to request and assign carriers to an exchange 
Nodes are able to understand when a disturbance node is present and avoid its frequencies 
For each RTS/CTS packet bursts can be sent

2023-02-22 22:03 UTC, fedefava86 requested changes

2023-02-22 22:03 UTC, fedefava86 commented on DESERT_Framework/DESERT/samples/desert_samples/MAC/test_uwcbr_smartofdm.tcl
> +        puts "example: ns test_uwcbr_smart_ofdm_mhop.tcl 5 fullBandexp.xls 5 f BPSK"
This example does not refer to this tcl, because the filename is different and it has less params

2023-02-22 22:03 UTC, fedefava86 commented on DESERT_Framework/DESERT/samples/desert_samples/MAC/test_uwcbr_smartofdm.tcl
> +        puts "The script requires five inputs:"
There are way more than five inputs :)

2023-02-22 22:03 UTC, fedefava86 commented on DESERT_Framework/DESERT/samples/desert_samples/MAC/test_uwcbr_smartofdm.tcl
> +set opt(bash_parameters)    1
this is already present at line 72, so here you are overwriting its value.

2023-02-22 22:03 UTC, fedefava86 commented on DESERT_Framework/DESERT/samples/desert_samples/MAC/test_uwcbr_smartofdm.tcl
> +if {$opt(bash_parameters)} {
I guess the intended way is to have a possibility not to indicate every param in the commandline. However, this is not working, 'cause you do not have the default values for every params. For example, if you disable the commandline params, `opt(fullBand)` member of associative array does not exists:

```
can't read "opt(fullBand)": no such element in array
    while executing
"if {$opt(fullBand) == 1} {
    set opt(ctrlCar) 0
}"
    (file "test_uwcbr_smartofdm.tcl" line 196)
```

2023-02-22 22:03 UTC, fedefava86 commented on DESERT_Framework/DESERT/data_link/uw-smart-ofdm/uw-smart-ofdm.cpp
> +	mac2phy_delay_ = 1e-19;
This is probably not necessary as not used. I guess parent class set it at the same value

2023-02-22 22:03 UTC, fedefava86 commented on DESERT_Framework/DESERT/data_link/uw-smart-ofdm/uw-smart-ofdm.cpp
> +		double RTS_Backoff;
If i understand correctly, in this case you are not sending RTS because you do not have any carrier available. However, you are not freeing the memory allocated for the current RTS and you are not storing the pointer anywhere, thus you are losing the reference to it, resulting in a memory leak. Am i correct?

2023-02-22 22:03 UTC, fedefava86 commented on DESERT_Framework/DESERT/data_link/uw-smart-ofdm/uw-smart-ofdm.cpp
> +		msgDisp.printStatus("No matching carriers, back to idle", "txCTS", NOW, addr);
same as RTS, you are loosing reference to CTS, resulting in a memory leak

2023-02-22 22:03 UTC, fedefava86 commented on DESERT_Framework/DESERT/data_link/uw-smart-ofdm/uw-smart-ofdm.cpp
> +			msgDisp.printStatus("New data but RTSvalid = FALSE", "stateIdle", NOW, addr);
in this case you print the status message and then exit from method? is there any other action you should do?

2023-02-22 22:03 UTC, fedefava86 commented on DESERT_Framework/DESERT/data_link/uw-smart-ofdm/uw-smart-ofdm.cpp
> +	int freec[10];
Usuallly we try to avoid "magic numbers" around the code. Better to define a constant, that helps you understand why the array should be exactly 10 elements long

2023-02-28 20:43 UTC, sarafalleni05 commented on DESERT_Framework/DESERT/data_link/uw-smart-ofdm/uw-smart-ofdm.cpp
> +	mac2phy_delay_ = 1e-19;
I'll remove it but the other modules extending MMac also have the definition on mac2phy_delay_, that I think it's what you are focusing on

2023-02-28 21:45 UTC, sarafalleni05 commented on DESERT_Framework/DESERT/data_link/uw-smart-ofdm/uw-smart-ofdm.cpp
> +			msgDisp.printStatus("New data but RTSvalid = FALSE", "stateIdle", NOW, addr);
That is correct. When the RTS Timer expires a new cycle of operations will be triggered and RTSvalid will go to 1

2023-03-01 08:20 UTC, fedefava86 approved these changes

2023-03-01 08:20 UTC, merged